name: Deploy Frontend

on:
  push:
    branches:
      - main

jobs:
  deploy-frontend:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Adjust version according to your setup

      - name: Sync Frontend Directory
        run: |
          rsync -av --delete /home/ubuntu/frontend/actions-runner/_work/Md-Ashraful-Islam/Md-Ashraful-Islam/ /home/ubuntu/frontend/Md-Ashraful-Islam/

      - name: Install npm dependencies
        run: |
          cd /home/ubuntu/frontend/Md-Ashraful-Islam
          rm -rf node_modules
          npm install

      - name: Build Frontend
        run: |
          cd /home/ubuntu/frontend/Md-Ashraful-Islam
          NODE_ENV=production npm run build
          sudo cp -r ./dist/* /var/www/html

      - name: Restart Nginx
        run: |
          sudo systemctl restart nginx
