name: Deploy Frontend

on:
  push:
    branches:
      - main

jobs:
  deploy-frontend:
    runs-on: self-hosted
    timeout-minutes: 20  # Adjust timeout as needed

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
          
      - name: Build and Deploy Frontend
        run: |
          cd /home/ubuntu/frontend/Md-Ashraful-Islam
          npm install
          npm run build
      - name: Sync Frontend Directory
        run: |
          rsync -av --delete /home/ubuntu/frontend/actions-runner/_work/Md-Ashraful-Islam/Md-Ashraful-Islam/ /home/ubuntu/frontend/Md-Ashraful-Islam/

      - name: Deploy Built Files
        run: |
          sudo cp -r /home/ubuntu/frontend/Md-Ashraful-Islam/* /var/www/html

      - name: Restart Nginx
        run: |
          sudo systemctl restart nginx