name: Deploy Frontend

on:
  push:
    branches:
      - main

jobs:
  deploy-frontend:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Sync Frontend Directory
        run: |
          rsync -av --delete /home/ubuntu/frontend/actions-runner/_work/Md-Ashraful-Islam/Md-Ashraful-Islam/ /home/ubuntu/frontend/Md-Ashraful-Islam/

      - name: Install npm dependencies
        run: |
          cd /home/ubuntu/frontend/Md-Ashraful-Islam
          npm install 2>&1 | tee npm-install.log

      - name: Build Frontend
        run: |
     cd /home/ubuntu/frontend/ Md-Ashraful-Islam
     NODE_ENV=production npm run build 2>&1 | tee npm-build.log
     # Example: Check for 'Build complete' message in npm-build.log
     if grep -q 'Build complete' npm-build.log; then
      sudo cp -r ./dist/* /var/www/html
      else
      echo "Build process did not complete successfully."
      exit 1
     fi


      - name: Restart Nginx
        run: |
          sudo systemctl restart nginx
